name: Test Coveralls

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install pnpm 7.14.0
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.14.0

    - name: pnpm install, pnpm test:coverage
      run: |
        pnpm install
        pnpm run test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
