name: Danger
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    danger:
        name: Danger
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install pnpm 9.12.3
              uses: pnpm/action-setup@v4
              with:
                  version: 9.12.3

            - name: Install dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Danger
              run: pnpm danger ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
