name: Danger
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    danger:
        name: Danger
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install pnpm 7.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.x.x

            - name: Install dependencies
              run: pnpm install

            - name: Danger
              run: pnpm danger ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
