name: Danger
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches: [main]
    workflow_dispatch:
jobs:
    danger:
        name: Danger
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install pnpm 7.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.x.x

            - name: Install dependencies
              run: pnpm install

            - name: Danger
              run: pnpm danger ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
