name: Documentation CI
on:
    pull_request:
        paths:
            - 'docs/**'
        branches: [master]

jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - name: Begin CI...
              uses: actions/checkout@v2

            - name: Use Node 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Deleting node_modules folder & Installing dependencies
              working-directory: ./docs
              run: npm ci

            - name: Building
              run: npm run build
              working-directory: ./docs
