name: CI
on:
    pull_request:
        paths-ignore:
            - 'packages/docs/**'
            - 'examples/**'
        branches: [main]
    workflow_dispatch:
jobs:
    coverage:
        name: Coverage report
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install pnpm 7.14.0
              uses: pnpm/action-setup@v2.2.4
              with:
                version: 7.14.0

            - name: Installing dependencies
              run: pnpm install

            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  skip-step: install
                  working-directory: ${{ matrix.path }}
                  test-script: pnpm run test:coverage --filter=[main...HEAD]
    build:
        name: Build, lint, and test ${{ matrix.name }} package on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['14.x', '16.x']
                os: [ubuntu-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install pnpm 7.14.0
              uses: pnpm/action-setup@v2.2.4
              with:
                version: 7.14.0

            - name: Install global dependencies
              run: pnpm install

            - name: Linting, testing & building changed packages
              run: pnpm turbo run lint test build --filter=[main...HEAD]
