name: CI
on:
    pull_request:
        paths-ignore:
            - 'packages/docs/**'
            - 'examples/**'
        branches: [main]
    workflow_dispatch:
jobs:
    generate_matrix:
        name: Get changed packages
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        outputs:
            names: ${{ steps.changed_packages.outputs.names }}
            paths: ${{ steps.changed_packages.outputs.paths }}
            empty: ${{ steps.changed_packages.outputs.empty }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Find changed packages
              id: changed_packages
              uses: alexshukel/get-changed-workspaces-action@v1.0.0
    coverage:
        name: Coverage report
        if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
        needs: [generate_matrix]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                path: ${{ fromJson(needs.generate_matrix.outputs.paths) }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install pnpm 7.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.x.x

            - name: Installing dependencies
              run: pnpm install

            - name: Debug
              run: echo ${{ matrix.path }}

            - uses: artiomtr/jest-coverage-report-action@v2.1.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  skip-step: install
                  test-script: pnpm turbo run test:coverage --filter=...[origin/${{ github.base_ref }}]
                  package-manager: pnpm
                  coverage-file: report.json
                  base-coverage-file: report.json
                  working-directory: ${{ matrix.path }}
    build:
        name: Build, lint, and test changed packages on Node 16
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 16
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install pnpm 7.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.x.x

            - name: Install global dependencies
              run: pnpm install

            - name: Linting, testing & building changed packages
              run: pnpm turbo run lint test build --filter=...[origin/${{ github.base_ref }}]

            - name: Check files format
              run: pnpm run format:check

            - name: Check for changeset existence
              run: pnpm changeset status --since=origin/main
