name: CI
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    format_files:
        name: Format and commit files
        runs-on: ubuntu-latest
        outputs:
            skip: ${{ steps.commit.outputs.skip == 'true' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Checkout branch
              run: |
                  git config pull.rebase true
                  git fetch
                  git checkout $GITHUB_HEAD_REF
                  git pull origin $GITHUB_HEAD_REF

            - name: Use Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install pnpm 7.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.x.x

            - name: Install global dependencies
              run: pnpm install

            - name: Format files
              run: pnpm run format

            - name: Commit changed files
              id: commit
              shell: bash
              run: |
                  if [[ `git status --porcelain` ]]; then
                      git add .
                      git config user.name "github-actions[bot]"
                      git config user.email "github-actions@github.com"
                      git commit -m "Syncpack and prettier format"
                      git push origin HEAD:"$GITHUB_HEAD_REF"
                      git push
                      echo "skip=true" >> $GITHUB_OUTPUT
                  else
                      echo "skip=false" >> $GITHUB_OUTPUT
                  fi

    generate_matrix:
        name: Get changed packages
        runs-on: ubuntu-latest
        needs: [format_files]
        # if: '!needs.format_files.outputs.skip'
        outputs:
            packages: ${{ steps.changed_packages.outputs.packages }}
            empty: ${{ steps.changed_packages.outputs.empty }}
        steps:
            - name: Debug
              run: echo ${{ needs.format_files.outputs.skip }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Find changed packages
              id: changed_packages
              uses: alexshukel/get-changed-workspaces-action@v2.0.0
              with:
                  filter: '@reactive-forms/*'

    coverage:
        name: Coverage report
        needs: [generate_matrix]
        if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ${{ fromJson(needs.generate_matrix.outputs.packages) }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install pnpm 7.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.x.x

            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  test-script: pnpm run --prefix ../.. turbo run test --filter ${{ matrix.package.name }}
                  package-manager: pnpm
                  working-directory: ${{ matrix.package.path }}

    size:
        name: Size limit
        runs-on: ubuntu-latest
        needs: [format_files]
        if: '!needs.format_files.outputs.skip'
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install pnpm 7.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.x.x

            - name: Size limit
              uses: andresz1/size-limit-action@dd31dce7dcc72a041fd3e49abf0502b13fc4ce05
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  package_manager: pnpm

    build:
        name: Build, lint, and test changed packages on Node 18
        needs: [format_files]
        if: '!needs.format_files.outputs.skip'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install pnpm 7.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.x.x

            - name: Install global dependencies
              run: pnpm install

            - name: Linting, testing & building changed packages
              run: pnpm turbo run lint test build --filter=...[origin/${{ github.base_ref }}]
