name: CI
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
jobs:
    generate_matrix:
        name: Get changed packages
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.changed_packages.outputs.packages }}
            empty: ${{ steps.changed_packages.outputs.empty }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Find changed packages
              id: changed_packages
              uses: alexshukel/get-changed-workspaces-action@v2.0.0
              with:
                  filter: '@reactive-forms/*'

    coverage:
        name: Coverage report
        needs: [generate_matrix]
        if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ${{ fromJson(needs.generate_matrix.outputs.packages) }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install pnpm 8.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.x.x

            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  test-script: pnpm run --prefix ../.. turbo run test --filter ${{ matrix.package.name }}
                  package-manager: pnpm
                  working-directory: ${{ matrix.package.path }}

    size:
        # TODO: configure Size limit for all packages
        name: Size limit
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install pnpm 8.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.x.x

            - name: Size limit
              uses: andresz1/size-limit-action@dd31dce7dcc72a041fd3e49abf0502b13fc4ce05
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  package_manager: pnpm

    build:
        name: Build, lint, and test changed packages on Node 18
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install pnpm 8.x.x
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.x.x

            - name: Install global dependencies
              run: pnpm install

            - name: Linting, testing & building changed packages
              run: pnpm turbo run lint test build --filter=...[origin/${{ github.base_ref }}]
