name: CI
on:
    pull_request:
        paths:
            - 'packages/**'
        branches: [master]
jobs:
    size:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install dependencies
              run: npm install

            - name: Bootstrap packages
              run: lerna bootstrap

            - name: Build packages
              run: npm run build

            - name: Size limit
              uses: andresz1/size-limit-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  skip_step: build
    danger:
        name: Danger
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install deps (with cache)
              uses: bahmutov/npm-install@v1

            - name: Danger
              run: npx danger ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    generate_matrix:
        name: Get changed packages
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.changed_packages.outputs.matrix }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Find changed packages
              id: changed_packages
              uses: giautm/matrix-git-generator@master
              with:
                  filters: |
                      packages/*/**:3
    build:
        needs: [generate_matrix]
        name: Build, lint, and test ${{ matrix.package }} package on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['10.x', '12.x', '14.x']
                package: ${{ fromJson(needs.generate_matrix.outputs.packages) }}
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: ${{ matrix.package }}

            - name: Lint
              run: yarn lint
              working-directory: ${{ matrix.package }}

            - name: Test
              run: yarn test --ci --coverage --maxWorkers=2
              working-directory: ${{ matrix.package }}

            - name: Build
              run: yarn build
              working-directory: ${{ matrix.package }}
