name: CI
on:
    pull_request:
        paths-ignore:
            - 'packages/docs/**'
            - 'examples/**'
        branches: [main]
    workflow_dispatch:
jobs:
    coverage:
        name: Coverage report
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install pnpm 7.14.0
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.14.0

            - name: Installing dependencies
              run: pnpm install

            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  skip-step: install
                  test-script: pnpm turbo run test:coverage --filter=...[origin/${{ github.base_ref }}]
    build:
        name: Build, lint, and test changed packages on Node 16
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node 16
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install pnpm 7.14.0
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.14.0

            - name: Install global dependencies
              run: pnpm install

            - name: Linting, testing & building changed packages
              run: pnpm turbo run lint test build --filter=...[origin/${{ github.base_ref }}]

            - name: Check files format
              run: pnpm run format:check
