name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        permissions:
            pull-requests: write
            id-token: write
            contents: write
        timeout-minutes: 5
        name: Release
        runs-on: windows-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install pnpm 9.12.3
              uses: pnpm/action-setup@v4
              with:
                  version: 9.12.3

            - name: Install dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Creating .npmrc
              run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
              env:
                  NPM_TOKEN: ${{ secrets.NPM_BOT_TOKEN }}

            - name: Create Release Pull Request or Publish to npm
              uses: changesets/action@v1
              with:
                  version: pnpm bump
                  # TODO do not make tag for @reactive-tools/eslint-config
                  publish: pnpm release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true
