name: Size Limit
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches: [main]
    workflow_dispatch:
jobs:
    size:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Size limit
              uses: andresz1/size-limit-action@v1.7.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  package_manager: pnpm
                  build_script: pnpm run build
