name: Size Limit
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches: [main]
    workflow_dispatch:
jobs:
    size:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install pnpm 7.14.0
              uses: pnpm/action-setup@v2.2.4
              with:
                version: 7.14.0

            - name: Install dependencies
              run: pnpm install

            - name: Build packages
              run: pnpm run build

            - name: Size limit
              uses: andresz1/size-limit-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  skip_step: build
