name: Syncpack
on:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    syncpack:
        name: syncpack
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node 18
              uses: actions/setup-node/v3
              with:
                  node-version: 18

            - uses: JamieMason/syncpack-github-action@0.2.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  package-manager: pnpm
